server:
  port: 9898
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:db_prod
    driver-class-name: org.h2.Driver
eureka:
  client:
    enabled: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
papa: Papa Abdou
